// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkgOe-o71tF_Gjb9DywFzZzzCSkufkPp0',
    appId: '1:239148701346:web:f87822ba372afd3933e9fb',
    messagingSenderId: '239148701346',
    projectId: 'marsexplorerapp-524d2',
    authDomain: 'marsexplorerapp-524d2.firebaseapp.com',
    storageBucket: 'marsexplorerapp-524d2.firebasestorage.app',
    measurementId: 'G-8QH3D0X08Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFLXxUNOZTdsvHliKAsvybn7yKP80tpOI',
    appId: '1:239148701346:android:187ae5c6511d321033e9fb',
    messagingSenderId: '239148701346',
    projectId: 'marsexplorerapp-524d2',
    storageBucket: 'marsexplorerapp-524d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHJ1FYS9j9hj3TZ4oXNsK_B0-7rZup00',
    appId: '1:239148701346:ios:c2c511b19fcb2ffa33e9fb',
    messagingSenderId: '239148701346',
    projectId: 'marsexplorerapp-524d2',
    storageBucket: 'marsexplorerapp-524d2.firebasestorage.app',
    iosBundleId: 'com.example.marsExplorerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVHJ1FYS9j9hj3TZ4oXNsK_B0-7rZup00',
    appId: '1:239148701346:ios:c2c511b19fcb2ffa33e9fb',
    messagingSenderId: '239148701346',
    projectId: 'marsexplorerapp-524d2',
    storageBucket: 'marsexplorerapp-524d2.firebasestorage.app',
    iosBundleId: 'com.example.marsExplorerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkgOe-o71tF_Gjb9DywFzZzzCSkufkPp0',
    appId: '1:239148701346:web:1f1f01600f974d6133e9fb',
    messagingSenderId: '239148701346',
    projectId: 'marsexplorerapp-524d2',
    authDomain: 'marsexplorerapp-524d2.firebaseapp.com',
    storageBucket: 'marsexplorerapp-524d2.firebasestorage.app',
    measurementId: 'G-NBZJ36HE3H',
  );
}
